version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html # Directly map src to /var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  php:
    build:
      context: .
      args:
        VERSION: ${VERSION:-} # Pass VERSION from .env as a build argument
    user: 1000:1000
    volumes:
      - ./src:/var/www/html # Ensures src on the host mirrors in php container
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=opencart
      - MYSQL_PASSWORD=opencart
      - MYSQL_DATABASE=opencart
      - VERSION=${VERSION:-} # Pass VERSION from .env to container environment
    expose:
      - "9000"
    restart: always

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: opencart
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: opencart
    depends_on:
      - mysql
    restart: always

  redis:
    image: redis:latest
    restart: always

  memcached:
    image: memcached:latest
    restart: always

volumes:
  db_data:
